description: |-
  Copyright 2021 <UCLA Mobility Lab>
  Author: Runsheng Xu <rxx3386@ucla.edu>
  Content: This is the scenario testing configuration file for v2x perception data dumping

# Define settings for multi-class blueprint spawning
# Comment out this chunk of code or set use_multi_class_bp to be False if you don't want to spawn multi-class actors
blueprint:
  use_multi_class_bp: true
  bp_meta_path: "opencda/assets/blueprint_meta/bbx_stats_0912.json" # Define the path for loading the blueprint metadata for defining the class of each blueprint
  # Define blueprint type sample probabilities
  bp_class_sample_prob:
    car: 0.5
    truck: 0.1
    bus: 0.2
    motorcycle: 0.1


# Define the basic parameters of the vehicles
vehicle_base:
  sensing:
      activate: false # when not activated, objects positions will be retrieved from server directly
      camera:
        visualize: 1 # how many camera images need to be visualized. 0 means no visualization for camera
        num: 4 # how many cameras are mounted on the vehicle. Maximum 3(frontal, left and right cameras)
        # relative positions (x,y,z,yaw) of the camera. len(positions) should be equal to camera num
        positions:
          - [2.5, 0, 1.0, 0]
          - [0.0, 0.3, 1.8, 100]
          - [0.0, -0.3, 1.8, -100]
          - [-2.0, 0.0, 1.5, 180]
      lidar: # lidar sensor configuration, check CARLA sensor reference for more details
        visualize: true
        channels: 128
        range: 120
        points_per_second: 2000000
        rotation_frequency: 20 # the simulation is 20 fps
        upper_fov: 10
        lower_fov: -30
        dropoff_general_rate: 0.05
        noise_stddev: 0.01
  map_manager:
    visualize: false
    activate: false
  
  safety_manager: # used to watch the safety status of the cav
    print_message: true # whether to print the message if hazard happens
    collision_sensor:
      history_size: 30
      col_thresh: 2
    stuck_dector:
      len_thresh: 500
      speed_thresh: 0.5
    offroad_dector: [ ]
    traffic_light_detector: # whether the vehicle violate the traffic light
      light_dist_thresh: 20
  behavior:
    max_speed: 50 # maximum speed, km/h
    tailgate_speed: 55 # when a vehicles needs to be close to another vehicle asap
    overtake_allowed: true # whether overtake allowed, typically false for platoon leader
    speed_lim_dist: 15
    speed_decrease: 5
    safety_time: 10
    collision_time_ahead: 5
    emergency_param: 3
    local_planner:  # trajectory planning related
      buffer_size: 12 # waypoint buffer size
      trajectory_update_freq: 15 # used to control trajectory points updating frequency
      waypoint_update_freq: 9 # used to control waypoint updating frequency
      min_dist: 3 # used to pop out the waypoints too close to current location
      trajectory_dt: 0.20 # for every dt seconds, we sample a trajectory point from the trajectory path as next goal state
      debug: false # whether to draw future/history waypoints
      debug_trajectory: false # whether to draw the trajectory points and path
  v2x:
    enabled: true

# define the background traffic control by carla
carla_traffic_manager:
  global_speed_perc: -100
  auto_lane_change: true
  random: true # whether to random select vehicles' color and model
  ignore_lights_percentage: 0 # whether set the traffic ignore traffic lights
  vehicle_list: ~  # a number or a list
  # Used only when vehicle_list is a number.
  #  x_min, x_max, y_min, y_max, x_step, y_step, vehicle_num
  range:
    # - [-11, 12, 100, 200, 3.5, 15, 25]
    - [-50, 50, 20, 250, 3.5, 5, 40]
# define scenario. In this scenario, a 4-vehicle platoon already exists.
scenario:
  rsu_list:
    - name: rsu1
      spawn_position: [0, 180, 3.0]
      id: -1

  single_cav_list:
    - name: cav1
      spawn_position: [5.854201, 184.692886, 0.275307, 0, -90, 0]
      destination: [5, 55.39, 0.275307]
      v2x:
        communication_range: 45
      behavior:
        local_planner:
          debug_trajectory: false
          debug: false

    - name: cav2
      spawn_position: [-25.969866, 134.663498, 0.275307, 0, 0, 0]
      destination: [1.498355, 62.019833, 0.275307]
      v2x:
        communication_range: 45
      behavior:
        local_planner:
          debug_trajectory: false
          debug: false
        # max_speed: 30 # maximum speed, km/h
        # tailgate_speed: 34 # when a vehicles needs to be close to another vehicle asap
        # speed_lim_dist: 10
        # overtake_allowed: true # whether overtake allowed, typically false for platoon leader
        # speed_decrease: 20
        # safety_time: 4
        # collision_time_ahead: 5
        # emergency_param: 0.4


